const vendor = {
    INITIALIZE_MENU: 'INITIALIZE_MENU',
    SET_MENU: 'SET_MENU',
    SET_LOADING: 'SET_LOADING',
    SET_PAGE_DATA: 'SET_PAGE_DATA',
    SET_FORM_DATA: 'SET_FORM_DATA',
    SHOW_HIDE_REDIRECTION_DIALOG: 'SHOW_HIDE_REDIRECTION_DIALOG',
    DELETE_RESOURCE: 'DELETE_RESOURCE'
}

const customer = {
    INITIALIZE_LISTING: 'INITIALIZE_LISTING',
    INITIALIZE_DETAIL: 'INITIALIZE_DETAIL',
    SET_RESOURCE_LIST: 'SET_RESOURCE_LIST',
    UPDATE_BOOKING_INFO: 'UPDATE_BOOKING_INFO',
    SHOW_BOOKING_MODAL: 'SHOW_BOOKING_MODAL',
    HIDE_BOOKING_MODAL: 'HIDE_BOOKING_MODAL',
    UPDATE_AVAILABILITY_AND_PRICE: 'UPDATE_AVAILABILITY_AND_PRICE',
    SET_SLOTS_DATA: 'SET_SLOTS_DATA',
    SET_SLOT_DATE: 'SET_SLOT_DATE'
}

const userData = {
    INITIALIZE_USER_DATA: 'INITIALIZE_USER_DATA',
    CALENDAR_DATA: 'CALENDAR_DATA',
    LOCATION_DATA: 'LOCATION_DATA'
}

const cart = {
    SET_CART_DATA: 'SET_CART_DATA',
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART'
}

const calendarData = {
    CALENDAR_DATA: 'CALENDAR_DATA',
    LOCATION_DATA: 'LOCATION_DATA',
    BOOKING_DATA: 'BOOKING_DATA'
}

const rateCalendarData = {
    RATE_LOCATION_DATA: "RATE_LOCATION_DATA",
    RATE_CALENDAR_DATA: "RATE_CALENDAR_DATA"
}

export default {
    ...vendor,
    ...userData,
    ...customer,
    ...cart,
    ...calendarData,
    ...rateCalendarData
};